version: '2.4'

services:
  everything:
    build: 
      context: ./
      dockerfile: ./Dockerfile
    image: everything:latest
    container_name: everything
    restart: always
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '2'
    volumes:
      - ./.reminders:/data/reminders/:rw
      - ./.codes:/data/codes:rw
      - ./config/config.toml:/config/config.toml:ro
